### ISSUE TITLE
SVG with stroke-dashoffset not getting rendered properly

### ISSUE THREAD

**Issue by ArunMichaelDsouza** [SamVerschueren/capture-pdf#3]
I am trying to convert an html file with a simple svg embedded in it - 

``` html
<svg width="200" height="200"> <circle fill="none" cx="100" cy="100" r="89" stroke="#aaa" stroke-width="20"></circle> <circle fill="none" cx="100" cy="100" r="89" stroke="#50a4e2" stroke-width="20" stroke-dasharray="559.2034923389832" stroke-dashoffset="223.68139693559328" transform="rotate(-90, 100, 100)"></circle></svg>
```

It should render something like this - 

![screen shot 2016-07-08 at 3 27 44 pm](https://cloud.githubusercontent.com/assets/4924614/16684074/9bedf560-4520-11e6-8838-7c17b5ec6fa9.png)

But in the generated PDF, its rendering like this -
![screen shot 2016-07-08 at 3 28 44 pm](https://cloud.githubusercontent.com/assets/4924614/16684100/c7fb31d6-4520-11e6-98f2-0309d6027360.png)

**Comment by SamVerschueren** [comment]
I'm afraid I can't do anything about it because it's phantom related. The only thing you can try is cloning the repository on your local machine, set the version of `phantom-bridge` to `2.0.1` and `npm install`. Then use that version to test if it works.

**Comment by ArunMichaelDsouza** [comment]
Its not working out.

**Comment by SamVerschueren** [comment]
The only thing I can recomend is trying to do this with [pageres](https://github.com/sindresorhus/pageres). If that's not working out either, it's definitely PhantomJS and out of my control.

**Comment by SamVerschueren** [comment]
Closing this as I believe it's a PhantomJS issue. If you think it's not the case, let me know and I'll reopen.
