### ISSUE TITLE
Electron support?

### ISSUE THREAD

**Issue by rcrodrigues** [SamVerschueren/capture-pdf#4]
Hey, I got here from the [phantom-html2pdf](https://github.com/bauhausjs/phantom-html2pdf/issues/23)
I'm searching for a library that supports Electron. I tried to run in my alectron app, but no success.
Got an error when spawning the child process. Probably because of ASAR files. Any tips maybe?

**Comment by SamVerschueren** [comment]
Not sure why it doesn't work. What's the error?

@sindresorhus Any ideas? It uses basically the same technique as `Pageres`. The only thing different is that I write to a temporary file and read that file again in order to return a `Buffer`.

**Comment by sindresorhus** [comment]
`child_process.spawn()` doesn't yet work with ASAR. See (and vote up!): https://github.com/electron/electron/issues/9459

**Comment by rcrodrigues** [comment]
Thanks @SamVerschueren  and @sindresorhus for the quick reply!

When using phanton-hmtl2pdf, in the convert method, i.g., a parameter of the child_process.spawn()
is a file inside the ASAR packed app files ("phantom-script.js"). As @sindresorhus  stated, I believe it's then an Electron problem.

**Comment by rcrodrigues** [comment]
Just letting you guys know, I managed to make it work in an Electron app by making the installer unpack this lib after the app is copied to the target, so it won't be located in ASAR file.  Thanks again for the support!

**Comment by SamVerschueren** [comment]
Thanks for the information regarding the topic @rcrodrigues and @sindresorhus. Going to close this as it's not something I can deal with from my side.
